patio108/urls.py
# django
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns 
from django.conf.urls import include
from django.views.generic import TemplateView
from django.conf.urls.static import static
# project
from django.conf import settings
from apps.connectors import urls as webhooks
from apps.api import urls as api
from apps.map.views import Map
from django.contrib.auth.views import LogoutView
from django.conf import settings

urlpatterns = [
    # admin
    path(
        'admin/',
        admin.site.urls
    ),
    path(
        'i18n/', 
        include('django.conf.urls.i18n')
    ),
    path(
        'logout',
        LogoutView.as_view(),
        { 'next_page': settings.LOGOUT_REDIRECT_URL },
        name='logout'
    ),
    # CKEditor
    path(
        'ckeditor/',
        include('ckeditor_uploader.urls')
    ),
    # webhooks
    path(
        'webhooks/',
        include(
            webhooks,
            namespace="webhooks"
        )
    ),
    # API
    # v1.0
    path(
        'api/1.0/',
        include(
            api,
        )
    ),
]

urlpatterns += i18n_patterns(
    # map related URLs
    path(
        '',
        Map.as_view(),
        name="map"
    ),
)

# Add static URLS when running a standalone server through manage.py
if settings.DEBUG == True:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root = settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root = settings.MEDIA_ROOT
    )

apps/map/models.py
# django
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.utils.text import slugify
from django.utils.timezone import now
from django.urls import reverse
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator 
from datetime import date
# contrib
from ckeditor_uploader.fields import RichTextUploadingField
from djgeojson.fields import PointField
from adminsortable.models import SortableMixin

# project
from django.conf import settings
from apps.model_utils.models import Category, Image, Link, Publishable
from . import validators

validator_video = validators.VideoTypeValidator()


class Hood(models.Model):
    
    name = models.CharField(
        _('Nombre del barrio'),
        max_length = 128,
        blank = False,
        null = True
    )
    
    name_es = models.CharField(
        _('Nombre del barrio en español'),
        max_length = 128,
        blank = True,
        null = True
    )
    
    lon = models.FloatField(
        _('Longitud del punto del barrio donde quieres centrar el mapa'),
        blank = True,
        null = True
    )
    
    lat = models.FloatField(
        _('Latitud del punto del barrio donde quieres centrar el mapa'),
        blank = True,
        null = True
    )
    
    class Meta:
        verbose_name        = _('barrio')
        verbose_name_plural = _('barrios')

    def __str__(self):
        return self.name


class TestimonyCategory(Category):

    content = RichTextUploadingField(
        _('Contenido'),
        blank=True,
        null=True
    )
    name_es = models.CharField(
        _('Nombre de la categoría en español'),
        max_length = 128,
        blank = False,
        null = True
    )
    content_es =  RichTextUploadingField(
        _('Contenido en español'),
        blank=True,
        null=True
    )
    image = models.ImageField(
        _('Imagen'),
        help_text = _(
            'Introduce opcionalmente una imagen de la categoría'
        ),
        upload_to='categories',
        null = True,
        blank = True,
    )

class Testimony(Publishable):

    name = models.CharField(
        _('Nombre'),
        max_length = 128,
        blank = False,
        null = True,
        help_text = _(
            'Nombre de la propuesta.'
        )
    )
    name_es = models.CharField(
        _('Nombre [es]'),
        max_length = 128,
        blank = False,
        null = True,
        help_text = _(
            'Nombre de la propuesta en español.'
        )
    )
    year = models.PositiveSmallIntegerField(
        _('Año de la propuesta'),
        blank = True,
        null = True,
        validators = [
            MinValueValidator(2000), 
            MaxValueValidator(2050)
        ],
        help_text = _(
            'Si lo dejas en blanco se usará el año actual.'
        )
    )
    person_name = models.CharField(
        _('Nombre de la persona que propone'),
        max_length = 128,
        blank = True,
        null = True,
    )
    person_age = models.PositiveSmallIntegerField(
        _('Edad de la persona que propone'),
        blank = True,
        null = True,
        validators = [
            MinValueValidator(1), 
            MaxValueValidator(100)
        ],
    )
    state = models.CharField(
        _('Estado de la propuesta'),
        max_length=2,
        choices=(
            ('0', _('No validada')),
            ('1', _('Validada')),
            ('2', _('Vehiculizada')),
        ),
        blank = False,
        default = 0,
        help_text = _(
            'Estado actual de la propuesta.'
        )
    )
    address = models.CharField(
        _('Lugar'),
        max_length = 128,
        blank = True,
        null = True,
        help_text = _(
            'Dirección de la propuesta. Esta información no se muestra, '
            'la puedes usar para guardar esta información de manera privada.'
        )
    )
    position = PointField(
        _('Sitúa tu historia'),
        blank = True,
        null = True,
        help_text = _(
            'Usa el localizador para encontrar tu ubicación pulsando en '
            'el botón "Buscar" tras escribir una dirección, por ejemplo: '
            '"Avenida de Miraflores" o "Plaza de España". '
            'Si todo es correcto esta se ubicará en el mapa. '
            'Si no la encuentras busca una cercana. Puedes ajustar la posición '
            'del marcador moviéndolo con el ratón pulsado.'
        )
    )
    category = models.ForeignKey(
        TestimonyCategory,
        verbose_name=_('¿De qué va principalmente tu historia?'),
        related_name='main_posts',
        blank=False,
        null=True,
        on_delete=models.SET_NULL,
    )
    other_categories = models.ManyToManyField(
        TestimonyCategory,
        verbose_name=_('¿Hay otras categorías relacionadas?'),
        related_name='other_posts',
        blank=True,
        help_text = _(
            'Manten presionado "Control" (o "Command" en un Mac) para seleccionar '
            'más de una opción o deseleccionar elementos.'
        )
    )
    summary = models.TextField(
        _('Descripción'),
        blank = False,
        null = True,
    )
    summary_es = models.TextField(
        _('Descripción [es]'),
        blank = False,
        null = True,
    )
    video = models.FileField(
        _('Sube el vídeo con tu historia'),
        help_text = _(
            'Puedes usar formatos ogg, mp4, avi, webm o mov'
        ),
        validators = [ validator_video ],
        blank=True,
        null=True
    )
    video_reply = models.FileField(
        _('Vídeo de respuesta'),
        help_text = _(
            'Puedes usar formatos ogg, mp4, avi, webm o mov'
        ),
        validators = [ validator_video ],
        blank=True,
        null=True
    )
    video_reply_text = models.TextField(
        _('Texto del video de respuesta'),
        blank = True,
        null = True,
        help_text = _(
            'Especifica opcionalmente un texto para acompañar '
            'al video de respuesta. Éste se mostará sobre el mismo.'
        )
    )
    video_reply_text_es = models.TextField(
        _('Texto del video de respuesta [es]'),
        blank = True,
        null = True,
        help_text = _(
            'Especifica opcionalmente un texto para acompañar '
            'al video de respuesta. Éste se mostará sobre el mismo.'
        )
    )
    name_reply = models.CharField(
        _('Nombre de la persona que responde'),
        max_length = 128,
        blank = True,
        null = True,
    )
    position_reply = models.CharField(
        _('Cargo de la persona que responde'),
        max_length = 128,
        blank = True,
        null = True,
    )
    position_reply_es = models.CharField(
        _('Cargo de la persona que responde [es]'),
        max_length = 128,
        blank = True,
        null = True,
    )
    link_url = models.URLField(
        _('Enlace a página externa'),
        blank = True,
        null = True,
        help_text = _(
            'Especifica opcionalmente un enlace a una web externa'
        ),
    )
    link_text = models.CharField(
        _('Texto del enlace'),
        max_length = 128,
        blank = True,
        null = True,
        help_text = _(
            'Especifica el texto del enlace. Si no pones nada se usará '
            'la misma URL del enlace.'
        )
    )
    link_helptext = models.CharField(
        _('Texto de ayuda del enlace'),
        max_length = 128,
        blank = True,
        null = True,
        help_text = _(
            'Especifica opcionalmente un texto para acompañar al enlace. '
            'Éste se mostrará sobre el mismo.'
        )
    )
    link_text_es = models.CharField(
        _('Texto del enlace [es]'),
        max_length = 128,
        blank = True,
        null = True,
        help_text = _(
            'Especifica el texto del enlace. Si no pones nada se usará '
            'la misma URL del enlace.'
        )
    )
    link_helptext_es = models.CharField(
        _('Texto de ayuda del enlace [es]'),
        max_length = 128,
        blank = True,
        null = True,
        help_text = _(
            'Especifica opcionalmente un texto para acompañar al enlace. '
            'Éste se mostrará sobre el mismo.'
        )
    )
    email = models.EmailField(
        _('Correo electrónico'),
        help_text = _(
            'Danos un correo electrónico para contactar contigo '
            'en caso necesario'
        ),
        blank=True,
        null=True
    )
    legal = models.BooleanField(
        _('Consentimiento'),
        blank=False,
        default=False,
        help_text = _(
            '<p>Consiento expresamente, conforme al Reglamento General de Protección '
            'de Datos 2016/679, a la cesión de mi imagen, proporcionada a el proyecto '
            'Patio108 a través de videotestimonio, siempre con el fin de desarrollar '
            'el proyecto Patio108.</p>'
            '<p>Los datos serán guardados por una duración indeterminada, si bien '
            'en cualquier momento el usuario podrá solicitar a Patio108 la supresión '
            'de los datos personales que le conciernan (a través de solicitud que '
            'se remitirá a la dirección de correo electrónico contacto@patio108.es).</p>'
        )
    )

    class Meta:
        verbose_name        = _('testimonio')
        verbose_name_plural = _('testimonios')

    def __str__(self):
        return self.name if self.name else 'Sin nombre todavía'

    def save(self, *args, **kwargs):
        """Populate automatically 'slug' field"""
        if not self.id and not self.slug:
            self.slug = slugify(self.name)
        if not self.year:

apps/map/forms.py
# django
from django import forms
from django.utils.translation import ugettext_lazy as _
# project
from .models import Testimony
from .widgets import GeocodedLeafletWidget

class TestimonyForm(forms.ModelForm):

    class Meta:
        model = Testimony
        fields = [
            'name',
            'category',
            'other_categories',
            'address',
            'video',
            'email',
            'legal'
        ]

    def __init__(self, *args, **kwargs):
        super(TestimonyForm,self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Elige una categoría'
        self.fields['email'].required = True
        self.fields['address'].required = True

apps/map/views.py
# django
from django.shortcuts import render
from django.views.generic import TemplateView
# project
from .models import Testimony, TestimonyCategory
from .forms import TestimonyForm


class Map(TemplateView):

    template_name = 'pages/map.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Map, self).get_context_data(*args, **kwargs)
        context['items'] = Testimony.objects.order_by('-creation_date')
        context['categories'] = TestimonyCategory.objects.all()
        context['form']       = TestimonyForm()
        return context

patio108/templates/pages/map.html
{% extends 'layouts/twocol.html' %} {% load static i18n textblock_tags leaflet_tags humanize %}

{% block html_title %}
    Hasiera
{% endblock %}

{% block body_classes %}
    page page--map
{% endblock %}

{% block header_end %}
    <link rel="stylesheet" href="{% static '/map/js/node_modules/leaflet/dist/leaflet.css' %}" />
{% endblock %}

{% block left %}
{% get_current_language as lang %}
<div class="site-header not-mobile">
    <div class="left">
        <div class="flex-between">
            {% include 'components/menu-langs.html' %}
            {% include 'components/menu-social.html' %}
        </div>
        <img class="site-logo" data-order="0" src="{% static logo_image %}" >
    </div>
    <div class="right">
        {% include 'components/menu-main.html' %}
    </div>
</div>
<div class="timeline-wrapper">
    <div class="timeline">
        {% for item in items %}
        <div class="timeline-item item-{{ item.pk }}" data-pk="{{ item.pk }}">
            <div class="timeline-item__meta {% if item.general == '1' %}star{% endif %}">
                <div class="timeline-item__date"></div>
                {% include 'components/share.html' with pk=item.pk title=item.name %}
            </div>
            {% if item.video %}
            <div class="timeline-item__video">
                <video
                  class="lazy"
                  preload="none"
                  data-src="{{ item.video.url }}"
                  controls
                  type="video/mp4"
                  controlsList="nodownload"
                >
                  <source data-src="{{ item.video.url}}">
                </video>
            </div>
            {% endif %}
            {% if item.name %}
            <h3 class="timeline-item__name">
                {% t item 'name' lang %}
            </h3>
            {% endif %}
            <div class="timeline-item__terms">
                
              {% if item.category %}{% t item.category 'name' lang %}{% endif %}{% if item.other_categories.all %}, {% for cat in item.other_categories.all %}{% t cat 'name' lang %}{% if not forloop.last %},{% endif %} {% endfor %}
                {% endif %}, {{ item.get_state_display }}
            </div>
            <div class="timeline-item__extra">
                <h4 class="timeline-item__person">
                  {% trans 'Propuesta' %}{% if item.person_name %}. {{ item.person_name }}{% endif %}
                </h4>
                <div class="timeline-item__summary">
                    {% t item 'summary' lang %}
                </div>
                {% if item.video_reply or item.video_reply_text %}
                    <h4 class="timeline-item__vireo-reply-label">
                      {% trans 'Respuesta' %}{% if item.name_reply %}. {{ item.name_reply }}{% endif %}{% if item.position_reply %}, {% t item 'position_reply' lang %}{% endif %}
                    </h4>
                    {% if item.video_reply_text %}
                    <div class="timeline-item__video-reply-text">
                        {% t item 'video_reply_text' lang %}
                    </div>
                    {% endif %}
                    {% if item.video_reply %}
                    <div class="timeline-item__video timeline-item__video--reply">
                        <video
                          class="lazy video-reply"
                          preload="none"
                          data-src="{{ item.video_reply.url }}"
                          controls
                          type="video/mp4"
                          controlsList="nodownload"
                        >
                          <source data-src="{{ item.video_reply.url}}">
                        </video>
                    </div>
                    {% endif %}
                {% endif %}
                {% if item.link_helptext %}
                <p class="timeline-item__link-prefix">
                      {% t item 'link_helptext' lang %}
                </p>
                {% endif %}
                {% if item.link_url %}
                <div class="timeline-item__link">
                    <a href="{{ item.link_url }}" target="_blank">
                        {% if item.link_text %}
                            {% t item 'link_text' lang %}
                        {% else %}
                            {{ item.link_url }}
                        {% endif %}
                    </a>
                </div>
                {% endif %}
                <button class="timeline-item__back">
                    {% trans 'Volver atrás' %}
                </button>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block right %}
{% get_current_language as lang %}
{% get_navigation as navigation %}
{% textblock 'info' as info_block %}

<div class="site-header mobile">
    <div class="left">
        <img class="site-logo" src="{% static logo_image %}" >
        {% include 'components/menu-social.html' %}
    </div>
    <div class="right">
        {% include 'components/menu-main.html' %}
    </div>
</div>
<div class="map-wrapper">
    {% include 'hood-search.html' %}
    <div id="map" class="full-height">
        <div class="legend">
            <h4 class="legend__label">
                {% t info_block 'title' lang %}
            </h4>
            <p class="legend__help">
                {% t info_block 'content' lang %}
            </p>
            <div class="legend__categories">
            </div>
        </div>
        <ul class="secondary-navigation">
            {% for item in navigation %}
                {% if item.navigation_visibility == '2' %}
                <li class="secondary-navigation__item" data-show="#{{ item.slug }}" data-hide=".modal">
                    {% t item 'title' lang %}
                </li>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
    {% for text in navigation %}
    <div class="modal swipe-left width-two-col" id="{{ text.slug }}">
        <img class="modal__close" data-close="#{{ text.slug }}" src="{% static 'site/img/icons/x.svg' %}" />
        <div class="modal__inner">
            <h2 class="modal__header">
                {% t text 'title' lang %}
            </h2>
            <div class="modal__body one-col">
                {% t text 'content' lang %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block footer_end %}
    {% if debug_js %}
    <script type="text/javascript" src="{% static '/map/js/dist/vendors~map.js' %}"></script>
    <script type="text/javascript" src="{% static '/map/js/dist/map.js' %}"></script>
    {% else %}
    <script type="text/javascript" src="{% static '/map/js/dist/vendors~map.min.js' %}"></script>
    <script type="text/javascript" src="{% static '/map/js/dist/map.min.js' %}"></script>
    {% endif %}
    {% if form %}
    <script type="text/javascript" src="{% static '/admin/js/vendor/jquery/jquery.min.js' %}"></script>
    {% endif %}
    <script src="{% static 'map/js/node_modules/vanilla-lazyload/dist/lazyload.min.js' %}"></script>
    <script>
        var lazyLoadInstance = new LazyLoad({});
    </script>
{% endblock %}